name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.craftaro.skyblock.SkyBlock
softdepend:
  - CMIEInjector
  - CoreProtect
  - EpicSpawners
  - Holograms
  - HolographicDisplays
  - LeaderHeads
  - PlaceholderAPI
  - PlayerPoints
  - Reserve
  - Residence
  - UltimateStacker
  - Vault
  - WorldEdit
loadbefore:
  - Multiverse-Core
  - ProtocolLib

author: Craftaro
authors: [ Fabrimat ]
website: ${project.url}

commands:
  island:
    description: Island command
    aliases: [ is ]
  skyblock:
    description: Skyblock info command.
