package me.goodandevil.skyblock.utils.world.block;

public enum BlockStateType {

	NORMAL, BANNER, BEACON, BREWINGSTAND, COMMANDBLOCK, CHEST, DISPENSER, DROPPER, HOPPER, SHULKERBOX, CREATURESPAWNER,
	ENDGATEWAY, FURNACE, JUKEBOX, SIGN, SKULL, DOUBLECHEST

}